# Generated by Django 4.2.23 on 2025-07-09 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("salaries", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
    ]
